name: Hexo Deploy

on:
  push:
    branches:
      - hexo

env:
  TZ: Asia/Shanghai

jobs:
  hexo-cicd:
    name: Hexo build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install hexo-cli -g
          npm install          

      - name: Deploy Hexo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          hexo deploy