name: Pages

on:
  push:
    branches:
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-artifact@v3
        with:
          name: pages
          path: ./public
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout Branch
        run: |
          git checkout gh-pages
      - name: Donwload Pages Artifacts
        uses: actions/download-artifact@v3
        with:
          name: pages
          path: release
      - name: Setting Git for release
        run: |
          mv .git ./release/.git
      - name: Deploy Hexo
        run: |
          cd ./release
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "CI: Auto update at $(date +"%m-%d %H:%M")"
          git push
